### ISSUE TITLE
Writeable xarray backend?

### ISSUE THREAD

**Issue by rabernat** [TileDB-Inc/TileDB-CF-Py#112]
Thanks for continuing to work on this integration effort. 🌟  I'm really excited about trying out TileDB from Xarray land!

Ideally, we would like to be able to not only _read_ but _write_ TileDB from Xarray. (I do appreciate that you have created a CLI for converting NetCDF, but often our data come from other sources or are derived on the fly.) There is no obvious way to achieve this with the current Xarray backend entry point API. I have opened up an issue - https://github.com/pydata/xarray/issues/5954 - to try to fix that.

Once that issue is resolved upstream, we (Pangeo) would be enthusiastic to work with you to get TileDB writing working. One motive for this is to be able to create TileDB data using [Pangeo Forge](https://pangeo-forge.readthedocs.io/). I hope you are open to the idea. 

Thanks again for all your excellent work here.

**Comment by jp-dark** [comment]
@rabernat Thank you for your interest! It would be great if Xarray adds an entry point API for writers as well as their current one for readers. We are planning on eventually implementing an Xarray-to-TileDB writer directly in this library, but if Xarray adds a writer API we will try to support that as well. I’ll keep an eye on the Xarray issue you linked.

**Comment by jp-dark** [comment]
PR #133 implements a writer from xarray to TileDB.
