### ISSUE TITLE
Option to add compression when converting netCDF to tileDB

### ISSUE THREAD

**Issue by eggio** [TileDB-Inc/TileDB-CF-Py#97]
Adding the option to a add tileDB filters (https://tiledb-inc-tiledb.readthedocs-hosted.com/en/1.6.3/tutorials/filters.html), exspecially compression to the converter.

**Comment by jp-dark** [comment]
Hi @eggio. You can currently add filters to the converter after it has been generated (see following comment). I am planning on adding a default attribute filter to the `add_array_creator` and `add_array_converter` methods in the `NetCDF4ConverterEngine`. I can also add the ability to set default attribute, dimension, and offset filters in the `from_file` and `from_group` methods in the `NetCDF4ConverterEngine`. Would that satisfy this feature request?

**Comment by jp-dark** [comment]
Examples below show how to set filters for the TileDB arrays generated from the `NetCDF4ConverterEngine`. It assumes `filter_list` is a FilterList object. For example,
```python
filter_list = tiledb.FilterList([tiledb.ZstdFilter(level=7)])
```

* Example setting filters for all attributes in a converter to the same filter list:
   ```python
   for array_creator in converter.array_creators():
       for attr_creator in array_creator:
           attr_creator.filters = filter_list
   ```
* Example setting filters for all dimensions in a converter to the same filter list:
   ```python
   for array_creator in converter.array_creators():
       array_creator.coords_filters  = filter_list
   ```
* Example setting all filters for offsets  in a converter (used for variable length attributes/dimensions) to the same filter list:
   ```python
   for array_creator in converter.array_creators():
       array_creator.offsets_filters = filter_list
   ```
* Example setting filters for a single attribute:
   ```python
   converter.get_array_creator("array_name").attr_creator("attr_name").filters = filter_list
   ```
* Example setting filters for a single dimension:
   ```python
   converter.get_array_creator("array_name").domain_creator.dim_creator("dim_name").filters = filter_list
   ```
* Example setting the offsets filters in a single array:
   ```python
   converter.get_array_creator("array_name").offsets_filters = filter_list
   ```

**Comment by eggio** [comment]
Thanks alot! Sorry for creating an Issue but i couldn't find it anywhere how to do it. I don't mind if you delete it.
